export enum DataType {
	CHAR = 'char',
	UCHAR = 'uchar',
	SHORT = 'short',
	USHORT = 'ushort',
	INT = 'int',
	UINT = 'uint',
	FLOAT = 'float',
	BOOLEAN = 'bool',
	STRING = 'string',
	ENUM = 'enum',
	DATE = 'date',
	TIME = 'time',
	DATETIME = 'datetime',
	COLOR = 'color',
	BUTTON = 'button',
	SWITCH = 'switch',
	COVER = 'cover',
	UNKNOWN = 'unknown',
}

export enum ShortDataType {
	CHAR = 'i8',
	UCHAR = 'u8',
	SHORT = 'i16',
	USHORT = 'u16',
	INT = 'i32',
	UINT = 'u32',
	FLOAT = 'f',
	BOOLEAN = 'b',
	STRING = 's',
	ENUM = 'e',
	DATE = 'd',
	TIME = 't',
	DATETIME = 'dt',
}
