<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260910150558 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fb_accounts_module_accounts (account_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', account_state VARCHAR(255) DEFAULT \'not_activated\' NOT NULL, account_request_hash VARCHAR(255) DEFAULT NULL, account_last_visit DATETIME DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(account_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Application accounts\' ');
        $this->addSql('CREATE TABLE fb_accounts_module_accounts_details (detail_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', account_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', detail_first_name VARCHAR(100) NOT NULL, detail_last_name VARCHAR(100) NOT NULL, detail_middle_name VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, UNIQUE INDEX UNIQ_7F871BD69B6B5FBA (account_id), PRIMARY KEY(detail_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Accounts details\' ');
        $this->addSql('CREATE TABLE fb_accounts_module_emails (email_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', account_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', email_address VARCHAR(150) NOT NULL, email_default TINYINT(1) DEFAULT 0 NOT NULL, email_verified TINYINT(1) DEFAULT 0 NOT NULL, email_verification_hash VARCHAR(150) DEFAULT NULL, email_verification_created DATETIME DEFAULT NULL, email_verification_completed DATETIME DEFAULT NULL, email_visibility VARCHAR(255) DEFAULT \'public\' NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_84A231FB9B6B5FBA (account_id), UNIQUE INDEX email_address_unique (email_address), PRIMARY KEY(email_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Emails addresses\' ');
        $this->addSql('CREATE TABLE fb_accounts_module_identities (identity_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', account_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', identity_uid VARCHAR(50) NOT NULL, identity_token VARCHAR(255) NOT NULL, identity_state VARCHAR(255) DEFAULT \'active\' NOT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_6314493B9B6B5FBA (account_id), INDEX identity_state_idx (identity_state), UNIQUE INDEX identity_uid_unique (identity_uid), PRIMARY KEY(identity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Accounts identities\' ');
        $this->addSql('CREATE TABLE fb_devices_module_channels (channel_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', device_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', channel_category VARCHAR(100) DEFAULT \'generic\' NOT NULL, channel_identifier VARCHAR(50) NOT NULL, channel_name VARCHAR(255) DEFAULT NULL, channel_comment LONGTEXT DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, channel_type VARCHAR(100) NOT NULL, INDEX IDX_7E8E41994A4C7D4 (device_id), INDEX channel_identifier_idx (channel_identifier), UNIQUE INDEX channel_identifier_unique (channel_identifier, device_id), PRIMARY KEY(channel_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Device channels\' ');
        $this->addSql('CREATE TABLE fb_devices_module_channels_controls (control_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', channel_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', control_name VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_FE9ECE2672F5A1AA (channel_id), INDEX control_name_idx (control_name), UNIQUE INDEX control_name_unique (control_name, channel_id), PRIMARY KEY(control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Device channels controls\' ');
        $this->addSql('CREATE TABLE fb_devices_module_channels_properties (property_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', channel_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', parent_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', property_category VARCHAR(100) DEFAULT \'generic\' NOT NULL, property_identifier VARCHAR(50) NOT NULL, property_name VARCHAR(255) DEFAULT NULL, property_settable TINYINT(1) DEFAULT 0 NOT NULL, property_queryable TINYINT(1) DEFAULT 0 NOT NULL, property_data_type VARCHAR(100) DEFAULT \'unknown\' NOT NULL, property_unit VARCHAR(20) DEFAULT NULL, property_format LONGTEXT DEFAULT NULL, property_invalid VARCHAR(255) DEFAULT NULL, property_scale INT DEFAULT NULL, property_step DOUBLE PRECISION DEFAULT NULL, property_value VARCHAR(255) DEFAULT NULL, property_default VARCHAR(255) DEFAULT NULL, property_value_transformer VARCHAR(255) DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, property_type VARCHAR(100) NOT NULL, INDEX IDX_8411BC1072F5A1AA (channel_id), INDEX IDX_8411BC10727ACA70 (parent_id), INDEX property_identifier_idx (property_identifier), INDEX property_settable_idx (property_settable), INDEX property_queryable_idx (property_queryable), UNIQUE INDEX property_identifier_unique (property_identifier, channel_id), PRIMARY KEY(property_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Device channels properties\' ');
        $this->addSql('CREATE TABLE fb_devices_module_connectors (connector_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', connector_category VARCHAR(100) DEFAULT \'generic\' NOT NULL, connector_identifier VARCHAR(50) NOT NULL, connector_name VARCHAR(255) DEFAULT NULL, connector_comment LONGTEXT DEFAULT NULL, connector_enabled TINYINT(1) DEFAULT 1 NOT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, connector_type VARCHAR(100) NOT NULL, INDEX connector_name_idx (connector_name), INDEX connector_enabled_idx (connector_enabled), UNIQUE INDEX connector_identifier_unique (connector_identifier), PRIMARY KEY(connector_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Communication connectors\' ');
        $this->addSql('CREATE TABLE fb_devices_module_connectors_controls (control_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', connector_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', control_name VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_6486C5284D085745 (connector_id), INDEX control_name_idx (control_name), UNIQUE INDEX control_name_unique (control_name, connector_id), PRIMARY KEY(control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Connectors controls\' ');
        $this->addSql('CREATE TABLE fb_devices_module_connectors_properties (property_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', connector_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', property_category VARCHAR(100) DEFAULT \'generic\' NOT NULL, property_identifier VARCHAR(50) NOT NULL, property_name VARCHAR(255) DEFAULT NULL, property_settable TINYINT(1) DEFAULT 0 NOT NULL, property_queryable TINYINT(1) DEFAULT 0 NOT NULL, property_data_type VARCHAR(100) DEFAULT \'unknown\' NOT NULL, property_unit VARCHAR(20) DEFAULT NULL, property_format LONGTEXT DEFAULT NULL, property_invalid VARCHAR(255) DEFAULT NULL, property_scale INT DEFAULT NULL, property_step DOUBLE PRECISION DEFAULT NULL, property_value VARCHAR(255) DEFAULT NULL, property_default VARCHAR(255) DEFAULT NULL, property_value_transformer VARCHAR(255) DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, property_type VARCHAR(100) NOT NULL, INDEX IDX_8D40D20E4D085745 (connector_id), INDEX property_identifier_idx (property_identifier), INDEX property_settable_idx (property_settable), INDEX property_queryable_idx (property_queryable), UNIQUE INDEX property_identifier_unique (property_identifier, connector_id), PRIMARY KEY(property_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Connectors properties\' ');
        $this->addSql('CREATE TABLE fb_devices_module_devices (device_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', connector_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', device_category VARCHAR(100) DEFAULT \'generic\' NOT NULL, device_identifier VARCHAR(50) NOT NULL, device_name VARCHAR(255) DEFAULT NULL, device_comment LONGTEXT DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, device_type VARCHAR(100) NOT NULL, INDEX IDX_39B4B08C4D085745 (connector_id), INDEX device_identifier_idx (device_identifier), INDEX device_name_idx (device_name), UNIQUE INDEX device_identifier_unique (device_identifier, connector_id), PRIMARY KEY(device_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Devices\' ');
        $this->addSql('CREATE TABLE fb_devices_module_devices_children (child_device BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', parent_device BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', INDEX IDX_2E8FECF0607A72D2 (child_device), INDEX IDX_2E8FECF0463C7548 (parent_device), PRIMARY KEY(child_device, parent_device)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fb_devices_module_devices_controls (control_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', device_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', control_name VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_75F5D17594A4C7D4 (device_id), INDEX control_name_idx (control_name), UNIQUE INDEX control_name_unique (control_name, device_id), PRIMARY KEY(control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Devices controls\' ');
        $this->addSql('CREATE TABLE fb_devices_module_devices_properties (property_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', device_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', parent_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', property_category VARCHAR(100) DEFAULT \'generic\' NOT NULL, property_identifier VARCHAR(50) NOT NULL, property_name VARCHAR(255) DEFAULT NULL, property_settable TINYINT(1) DEFAULT 0 NOT NULL, property_queryable TINYINT(1) DEFAULT 0 NOT NULL, property_data_type VARCHAR(100) DEFAULT \'unknown\' NOT NULL, property_unit VARCHAR(20) DEFAULT NULL, property_format LONGTEXT DEFAULT NULL, property_invalid VARCHAR(255) DEFAULT NULL, property_scale INT DEFAULT NULL, property_step DOUBLE PRECISION DEFAULT NULL, property_value VARCHAR(255) DEFAULT NULL, property_default VARCHAR(255) DEFAULT NULL, property_value_transformer VARCHAR(255) DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, property_type VARCHAR(100) NOT NULL, INDEX IDX_988F341994A4C7D4 (device_id), INDEX IDX_988F3419727ACA70 (parent_id), INDEX property_identifier_idx (property_identifier), INDEX property_settable_idx (property_settable), INDEX property_queryable_idx (property_queryable), UNIQUE INDEX property_identifier_unique (property_identifier, device_id), PRIMARY KEY(property_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Devices properties\' ');
        $this->addSql('CREATE TABLE fb_devices_module_ui_module_bridge_channels_data_sources (data_source_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', data_source_property BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', UNIQUE INDEX UNIQ_8D605470BD63C31B (data_source_property), PRIMARY KEY(data_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Widget data source connection to channel\' ');
        $this->addSql('CREATE TABLE fb_devices_module_ui_module_bridge_connectors_data_sources (data_source_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', data_source_property BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', UNIQUE INDEX UNIQ_3AC0FC69BD63C31B (data_source_property), PRIMARY KEY(data_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Widget data source connection to connector\' ');
        $this->addSql('CREATE TABLE fb_devices_module_ui_module_bridge_devices_data_sources (data_source_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', data_source_property BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', UNIQUE INDEX UNIQ_99741E8BBD63C31B (data_source_property), PRIMARY KEY(data_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Widget data source connection to device\' ');
        $this->addSql('CREATE TABLE fb_homekit_connector_clients (client_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', connector_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', client_uid VARCHAR(255) NOT NULL, client_public_key VARBINARY(255) NOT NULL, client_admin TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_FC6FC7B14D085745 (connector_id), UNIQUE INDEX client_uid_unique (client_uid, connector_id), PRIMARY KEY(client_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'HomeKit connector clients\' ');
        $this->addSql('CREATE TABLE fb_security_policies (policy_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', parent_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', ptype VARCHAR(255) NOT NULL, v0 VARCHAR(150) DEFAULT NULL, v1 VARCHAR(150) DEFAULT NULL, v2 VARCHAR(150) DEFAULT NULL, v3 VARCHAR(150) DEFAULT NULL, v4 VARCHAR(150) DEFAULT NULL, v5 VARCHAR(150) DEFAULT NULL, policy_type VARCHAR(100) NOT NULL, policy_comment VARCHAR(255) DEFAULT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_93942B39727ACA70 (parent_id), PRIMARY KEY(policy_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Casbin policies\' ');
        $this->addSql('CREATE TABLE fb_security_tokens (token_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', parent_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', identity_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', token_token LONGTEXT NOT NULL, token_state VARCHAR(255) DEFAULT \'active\' NOT NULL, token_type VARCHAR(100) NOT NULL, token_valid_till DATETIME DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_24A03773727ACA70 (parent_id), INDEX IDX_24A03773FF3ED4A8 (identity_id), PRIMARY KEY(token_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fb_triggers_module_actions (action_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', trigger_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', action_enabled TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, action_type VARCHAR(100) NOT NULL, INDEX IDX_EFF00DD45FDDDCD6 (trigger_id), PRIMARY KEY(action_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Triggers actions\' ');
        $this->addSql('CREATE TABLE fb_triggers_module_conditions (condition_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', trigger_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', condition_enabled TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, condition_type VARCHAR(100) NOT NULL, INDEX IDX_A1EB963D5FDDDCD6 (trigger_id), PRIMARY KEY(condition_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Triggers conditions\' ');
        $this->addSql('CREATE TABLE fb_triggers_module_notifications (notification_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', trigger_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid_binary)\', notification_enabled TINYINT(1) DEFAULT 1 NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, notification_type VARCHAR(100) NOT NULL, notification_email VARCHAR(255) DEFAULT NULL, notification_phone VARCHAR(150) DEFAULT NULL COMMENT \'(DC2Type:phone)\', INDEX IDX_FFCAC9E25FDDDCD6 (trigger_id), PRIMARY KEY(notification_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Triggers notifications\' ');
        $this->addSql('CREATE TABLE fb_triggers_module_triggers (trigger_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', trigger_name VARCHAR(100) NOT NULL, trigger_comment LONGTEXT DEFAULT NULL, trigger_enabled TINYINT(1) DEFAULT 1 NOT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, trigger_type VARCHAR(100) NOT NULL, PRIMARY KEY(trigger_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Actions triggers\' ');
        $this->addSql('CREATE TABLE fb_triggers_module_triggers_controls (control_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', trigger_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', control_name VARCHAR(100) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_53BE4B525FDDDCD6 (trigger_id), INDEX control_name_idx (control_name), UNIQUE INDEX trigger_control_unique (control_name, trigger_id), PRIMARY KEY(control_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Triggers controls\' ');
        $this->addSql('CREATE TABLE fb_ui_module_dashboards (dashboard_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', dashboard_identifier VARCHAR(255) NOT NULL, dashboard_name VARCHAR(255) DEFAULT NULL, dashboard_comment LONGTEXT DEFAULT NULL, dashboard_priority INT DEFAULT 0 NOT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, INDEX dashboard_name_idx (dashboard_name), PRIMARY KEY(dashboard_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'User interface widgets dashboards\' ');
        $this->addSql('CREATE TABLE fb_ui_module_groups (group_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', group_identifier VARCHAR(255) NOT NULL, group_name VARCHAR(255) DEFAULT NULL, group_comment LONGTEXT DEFAULT NULL, group_priority INT DEFAULT 0 NOT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, INDEX group_name_idx (group_name), PRIMARY KEY(group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Widget groups\' ');
        $this->addSql('CREATE TABLE fb_ui_module_widgets_groups (group_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', widget_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', INDEX IDX_BB3B6B12FE54D947 (group_id), INDEX IDX_BB3B6B12FBE885E2 (widget_id), PRIMARY KEY(group_id, widget_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fb_ui_module_tabs (tab_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', dashboard_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', tab_identifier VARCHAR(255) NOT NULL, tab_name VARCHAR(255) DEFAULT NULL, tab_comment LONGTEXT DEFAULT NULL, tab_priority INT DEFAULT 0 NOT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, INDEX IDX_13FBC290B9D04D2B (dashboard_id), INDEX tab_name_idx (tab_name), UNIQUE INDEX tab_identifier_unique (tab_identifier, dashboard_id), PRIMARY KEY(tab_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Widget tabs\' ');
        $this->addSql('CREATE TABLE fb_ui_module_widgets_tabs (tab_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', widget_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', INDEX IDX_FC0C73D08D0C9323 (tab_id), INDEX IDX_FC0C73D0FBE885E2 (widget_id), PRIMARY KEY(tab_id, widget_id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fb_ui_module_widgets (widget_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', widget_identifier VARCHAR(255) NOT NULL, widget_name VARCHAR(255) DEFAULT NULL, params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, owner VARCHAR(255) DEFAULT NULL, widget_type VARCHAR(100) NOT NULL, INDEX widget_type_idx (widget_type), PRIMARY KEY(widget_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'User interface widgets\' ');
        $this->addSql('CREATE TABLE fb_ui_module_widgets_data_sources (data_source_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', widget_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, data_source_type VARCHAR(100) NOT NULL, INDEX IDX_231033A6FBE885E2 (widget_id), INDEX data_source_type_idx (data_source_type), PRIMARY KEY(data_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'User interface widgets data sources\' ');
        $this->addSql('CREATE TABLE fb_ui_module_widgets_display (display_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', widget_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', params JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, display_type VARCHAR(100) NOT NULL, INDEX IDX_AF262485FBE885E2 (widget_id), INDEX display_type_idx (display_type), PRIMARY KEY(display_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'User interface widgets display settings\' ');
        $this->addSql('CREATE TABLE fb_ui_module_widgets_generic_data_sources (data_source_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', PRIMARY KEY(data_source_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'Widget generic data source\' ');
        $this->addSql('ALTER TABLE fb_accounts_module_accounts_details ADD CONSTRAINT FK_7F871BD69B6B5FBA FOREIGN KEY (account_id) REFERENCES fb_accounts_module_accounts (account_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_accounts_module_emails ADD CONSTRAINT FK_84A231FB9B6B5FBA FOREIGN KEY (account_id) REFERENCES fb_accounts_module_accounts (account_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_accounts_module_identities ADD CONSTRAINT FK_6314493B9B6B5FBA FOREIGN KEY (account_id) REFERENCES fb_accounts_module_accounts (account_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_channels ADD CONSTRAINT FK_7E8E41994A4C7D4 FOREIGN KEY (device_id) REFERENCES fb_devices_module_devices (device_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_channels_controls ADD CONSTRAINT FK_FE9ECE2672F5A1AA FOREIGN KEY (channel_id) REFERENCES fb_devices_module_channels (channel_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_channels_properties ADD CONSTRAINT FK_8411BC1072F5A1AA FOREIGN KEY (channel_id) REFERENCES fb_devices_module_channels (channel_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_channels_properties ADD CONSTRAINT FK_8411BC10727ACA70 FOREIGN KEY (parent_id) REFERENCES fb_devices_module_channels_properties (property_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_connectors_controls ADD CONSTRAINT FK_6486C5284D085745 FOREIGN KEY (connector_id) REFERENCES fb_devices_module_connectors (connector_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_connectors_properties ADD CONSTRAINT FK_8D40D20E4D085745 FOREIGN KEY (connector_id) REFERENCES fb_devices_module_connectors (connector_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_devices ADD CONSTRAINT FK_39B4B08C4D085745 FOREIGN KEY (connector_id) REFERENCES fb_devices_module_connectors (connector_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_devices_children ADD CONSTRAINT FK_2E8FECF0607A72D2 FOREIGN KEY (child_device) REFERENCES fb_devices_module_devices (device_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_devices_children ADD CONSTRAINT FK_2E8FECF0463C7548 FOREIGN KEY (parent_device) REFERENCES fb_devices_module_devices (device_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_devices_controls ADD CONSTRAINT FK_75F5D17594A4C7D4 FOREIGN KEY (device_id) REFERENCES fb_devices_module_devices (device_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_devices_properties ADD CONSTRAINT FK_988F341994A4C7D4 FOREIGN KEY (device_id) REFERENCES fb_devices_module_devices (device_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_devices_properties ADD CONSTRAINT FK_988F3419727ACA70 FOREIGN KEY (parent_id) REFERENCES fb_devices_module_devices_properties (property_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_channels_data_sources ADD CONSTRAINT FK_8D605470BD63C31B FOREIGN KEY (data_source_property) REFERENCES fb_devices_module_channels_properties (property_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_channels_data_sources ADD CONSTRAINT FK_8D6054701A935C57 FOREIGN KEY (data_source_id) REFERENCES fb_ui_module_widgets_data_sources (data_source_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_connectors_data_sources ADD CONSTRAINT FK_3AC0FC69BD63C31B FOREIGN KEY (data_source_property) REFERENCES fb_devices_module_connectors_properties (property_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_connectors_data_sources ADD CONSTRAINT FK_3AC0FC691A935C57 FOREIGN KEY (data_source_id) REFERENCES fb_ui_module_widgets_data_sources (data_source_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_devices_data_sources ADD CONSTRAINT FK_99741E8BBD63C31B FOREIGN KEY (data_source_property) REFERENCES fb_devices_module_devices_properties (property_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_devices_data_sources ADD CONSTRAINT FK_99741E8B1A935C57 FOREIGN KEY (data_source_id) REFERENCES fb_ui_module_widgets_data_sources (data_source_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_homekit_connector_clients ADD CONSTRAINT FK_FC6FC7B14D085745 FOREIGN KEY (connector_id) REFERENCES fb_devices_module_connectors (connector_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_security_policies ADD CONSTRAINT FK_93942B39727ACA70 FOREIGN KEY (parent_id) REFERENCES fb_security_policies (policy_id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fb_security_tokens ADD CONSTRAINT FK_24A03773727ACA70 FOREIGN KEY (parent_id) REFERENCES fb_security_tokens (token_id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fb_security_tokens ADD CONSTRAINT FK_24A03773FF3ED4A8 FOREIGN KEY (identity_id) REFERENCES fb_accounts_module_identities (identity_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_triggers_module_actions ADD CONSTRAINT FK_EFF00DD45FDDDCD6 FOREIGN KEY (trigger_id) REFERENCES fb_triggers_module_triggers (trigger_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_triggers_module_conditions ADD CONSTRAINT FK_A1EB963D5FDDDCD6 FOREIGN KEY (trigger_id) REFERENCES fb_triggers_module_triggers (trigger_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_triggers_module_notifications ADD CONSTRAINT FK_FFCAC9E25FDDDCD6 FOREIGN KEY (trigger_id) REFERENCES fb_triggers_module_triggers (trigger_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_triggers_module_triggers_controls ADD CONSTRAINT FK_53BE4B525FDDDCD6 FOREIGN KEY (trigger_id) REFERENCES fb_triggers_module_triggers (trigger_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_groups ADD CONSTRAINT FK_BB3B6B12FE54D947 FOREIGN KEY (group_id) REFERENCES fb_ui_module_groups (group_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_groups ADD CONSTRAINT FK_BB3B6B12FBE885E2 FOREIGN KEY (widget_id) REFERENCES fb_ui_module_widgets (widget_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_tabs ADD CONSTRAINT FK_13FBC290B9D04D2B FOREIGN KEY (dashboard_id) REFERENCES fb_ui_module_dashboards (dashboard_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_tabs ADD CONSTRAINT FK_FC0C73D08D0C9323 FOREIGN KEY (tab_id) REFERENCES fb_ui_module_tabs (tab_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_tabs ADD CONSTRAINT FK_FC0C73D0FBE885E2 FOREIGN KEY (widget_id) REFERENCES fb_ui_module_widgets (widget_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_data_sources ADD CONSTRAINT FK_231033A6FBE885E2 FOREIGN KEY (widget_id) REFERENCES fb_ui_module_widgets (widget_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_display ADD CONSTRAINT FK_AF262485FBE885E2 FOREIGN KEY (widget_id) REFERENCES fb_ui_module_widgets (widget_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_generic_data_sources ADD CONSTRAINT FK_B03B6A0B1A935C57 FOREIGN KEY (data_source_id) REFERENCES fb_ui_module_widgets_data_sources (data_source_id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fb_accounts_module_accounts_details DROP FOREIGN KEY FK_7F871BD69B6B5FBA');
        $this->addSql('ALTER TABLE fb_accounts_module_emails DROP FOREIGN KEY FK_84A231FB9B6B5FBA');
        $this->addSql('ALTER TABLE fb_accounts_module_identities DROP FOREIGN KEY FK_6314493B9B6B5FBA');
        $this->addSql('ALTER TABLE fb_devices_module_channels DROP FOREIGN KEY FK_7E8E41994A4C7D4');
        $this->addSql('ALTER TABLE fb_devices_module_channels_controls DROP FOREIGN KEY FK_FE9ECE2672F5A1AA');
        $this->addSql('ALTER TABLE fb_devices_module_channels_properties DROP FOREIGN KEY FK_8411BC1072F5A1AA');
        $this->addSql('ALTER TABLE fb_devices_module_channels_properties DROP FOREIGN KEY FK_8411BC10727ACA70');
        $this->addSql('ALTER TABLE fb_devices_module_connectors_controls DROP FOREIGN KEY FK_6486C5284D085745');
        $this->addSql('ALTER TABLE fb_devices_module_connectors_properties DROP FOREIGN KEY FK_8D40D20E4D085745');
        $this->addSql('ALTER TABLE fb_devices_module_devices DROP FOREIGN KEY FK_39B4B08C4D085745');
        $this->addSql('ALTER TABLE fb_devices_module_devices_children DROP FOREIGN KEY FK_2E8FECF0607A72D2');
        $this->addSql('ALTER TABLE fb_devices_module_devices_children DROP FOREIGN KEY FK_2E8FECF0463C7548');
        $this->addSql('ALTER TABLE fb_devices_module_devices_controls DROP FOREIGN KEY FK_75F5D17594A4C7D4');
        $this->addSql('ALTER TABLE fb_devices_module_devices_properties DROP FOREIGN KEY FK_988F341994A4C7D4');
        $this->addSql('ALTER TABLE fb_devices_module_devices_properties DROP FOREIGN KEY FK_988F3419727ACA70');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_channels_data_sources DROP FOREIGN KEY FK_8D605470BD63C31B');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_channels_data_sources DROP FOREIGN KEY FK_8D6054701A935C57');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_connectors_data_sources DROP FOREIGN KEY FK_3AC0FC69BD63C31B');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_connectors_data_sources DROP FOREIGN KEY FK_3AC0FC691A935C57');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_devices_data_sources DROP FOREIGN KEY FK_99741E8BBD63C31B');
        $this->addSql('ALTER TABLE fb_devices_module_ui_module_bridge_devices_data_sources DROP FOREIGN KEY FK_99741E8B1A935C57');
        $this->addSql('ALTER TABLE fb_homekit_connector_clients DROP FOREIGN KEY FK_FC6FC7B14D085745');
        $this->addSql('ALTER TABLE fb_security_policies DROP FOREIGN KEY FK_93942B39727ACA70');
        $this->addSql('ALTER TABLE fb_security_tokens DROP FOREIGN KEY FK_24A03773727ACA70');
        $this->addSql('ALTER TABLE fb_security_tokens DROP FOREIGN KEY FK_24A03773FF3ED4A8');
        $this->addSql('ALTER TABLE fb_triggers_module_actions DROP FOREIGN KEY FK_EFF00DD45FDDDCD6');
        $this->addSql('ALTER TABLE fb_triggers_module_conditions DROP FOREIGN KEY FK_A1EB963D5FDDDCD6');
        $this->addSql('ALTER TABLE fb_triggers_module_notifications DROP FOREIGN KEY FK_FFCAC9E25FDDDCD6');
        $this->addSql('ALTER TABLE fb_triggers_module_triggers_controls DROP FOREIGN KEY FK_53BE4B525FDDDCD6');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_groups DROP FOREIGN KEY FK_BB3B6B12FE54D947');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_groups DROP FOREIGN KEY FK_BB3B6B12FBE885E2');
        $this->addSql('ALTER TABLE fb_ui_module_tabs DROP FOREIGN KEY FK_13FBC290B9D04D2B');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_tabs DROP FOREIGN KEY FK_FC0C73D08D0C9323');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_tabs DROP FOREIGN KEY FK_FC0C73D0FBE885E2');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_data_sources DROP FOREIGN KEY FK_231033A6FBE885E2');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_display DROP FOREIGN KEY FK_AF262485FBE885E2');
        $this->addSql('ALTER TABLE fb_ui_module_widgets_generic_data_sources DROP FOREIGN KEY FK_B03B6A0B1A935C57');
        $this->addSql('DROP TABLE fb_accounts_module_accounts');
        $this->addSql('DROP TABLE fb_accounts_module_accounts_details');
        $this->addSql('DROP TABLE fb_accounts_module_emails');
        $this->addSql('DROP TABLE fb_accounts_module_identities');
        $this->addSql('DROP TABLE fb_devices_module_channels');
        $this->addSql('DROP TABLE fb_devices_module_channels_controls');
        $this->addSql('DROP TABLE fb_devices_module_channels_properties');
        $this->addSql('DROP TABLE fb_devices_module_connectors');
        $this->addSql('DROP TABLE fb_devices_module_connectors_controls');
        $this->addSql('DROP TABLE fb_devices_module_connectors_properties');
        $this->addSql('DROP TABLE fb_devices_module_devices');
        $this->addSql('DROP TABLE fb_devices_module_devices_children');
        $this->addSql('DROP TABLE fb_devices_module_devices_controls');
        $this->addSql('DROP TABLE fb_devices_module_devices_properties');
        $this->addSql('DROP TABLE fb_devices_module_ui_module_bridge_channels_data_sources');
        $this->addSql('DROP TABLE fb_devices_module_ui_module_bridge_connectors_data_sources');
        $this->addSql('DROP TABLE fb_devices_module_ui_module_bridge_devices_data_sources');
        $this->addSql('DROP TABLE fb_homekit_connector_clients');
        $this->addSql('DROP TABLE fb_security_policies');
        $this->addSql('DROP TABLE fb_security_tokens');
        $this->addSql('DROP TABLE fb_triggers_module_actions');
        $this->addSql('DROP TABLE fb_triggers_module_conditions');
        $this->addSql('DROP TABLE fb_triggers_module_notifications');
        $this->addSql('DROP TABLE fb_triggers_module_triggers');
        $this->addSql('DROP TABLE fb_triggers_module_triggers_controls');
        $this->addSql('DROP TABLE fb_ui_module_dashboards');
        $this->addSql('DROP TABLE fb_ui_module_groups');
        $this->addSql('DROP TABLE fb_ui_module_widgets_groups');
        $this->addSql('DROP TABLE fb_ui_module_tabs');
        $this->addSql('DROP TABLE fb_ui_module_widgets_tabs');
        $this->addSql('DROP TABLE fb_ui_module_widgets');
        $this->addSql('DROP TABLE fb_ui_module_widgets_data_sources');
        $this->addSql('DROP TABLE fb_ui_module_widgets_display');
        $this->addSql('DROP TABLE fb_ui_module_widgets_generic_data_sources');
    }
}
