import { library } from '@fortawesome/fontawesome-svg-core';
import {
	faAddressCard,
	faAngleLeft,
	faAngleRight,
	faArrowLeft,
	faArrowRight,
	faBaby,
	faBan,
	faBath,
	faBed,
	faBlender,
	faBolt,
	faCalculator,
	faCalendar,
	faClone,
	faChair,
	faChartBar,
	faChartLine,
	faCheck,
	faCheckCircle,
	faChevronRight,
	faCircle,
	faClipboard,
	faClock,
	faCog,
	faCogs,
	faCouch,
	faCube,
	faCubes,
	faDesktop,
	faEllipsisV,
	faEllipsisH,
	faEnvelope,
	faEthernet,
	faExclamation,
	faExclamationCircle,
	faExclamationTriangle,
	faFan,
	faFile,
	faFolder,
	faFolderPlus,
	faGamepad,
	faGlobe,
	faHome,
	faHotTub,
	faInfo,
	faInfoCircle,
	faKey,
	faLightbulb,
	faLock,
	faMagic,
	faMapMarkerAlt,
	faMicrochip,
	faMicrophoneAlt,
	faMinus,
	faMinusCircle,
	faMobile,
	faPauseCircle,
	faPencilAlt,
	faPlayCircle,
	faPlug,
	faPlus,
	faPlusCircle,
	faPowerOff,
	faProjectDiagram,
	faQuestionCircle,
	faRobot,
	faSatelliteDish,
	faSearch,
	faShower,
	faSignOutAlt,
	faSlidersH,
	faStar,
	faStopCircle,
	faStore,
	faSun,
	faSyncAlt,
	faSwimmingPool,
	faTableTennis,
	faTachometerAlt,
	faThermometerHalf,
	faTrashAlt,
	faTimes,
	faTint,
	faToggleOn,
	faToilet,
	faTv,
	faTrash,
	faUnlock,
	faUser,
	faUserCircle,
	faUsers,
	faUserShield,
	faWifi,
	faWindowClose,
} from '@fortawesome/free-solid-svg-icons';
import { faFacebook, faGithub, faTwitter } from '@fortawesome/free-brands-svg-icons';

export default {
	install: (): void => {
		library.add(faAddressCard);
		library.add(faAngleLeft);
		library.add(faAngleRight);
		library.add(faArrowLeft);
		library.add(faArrowRight);
		library.add(faBaby);
		library.add(faBan);
		library.add(faBath);
		library.add(faBed);
		library.add(faBlender);
		library.add(faBolt);
		library.add(faCalculator);
		library.add(faCalendar);
		library.add(faClone);
		library.add(faChair);
		library.add(faChartBar);
		library.add(faChartLine);
		library.add(faCheck);
		library.add(faCheckCircle);
		library.add(faChevronRight);
		library.add(faCircle);
		library.add(faClipboard);
		library.add(faClock);
		library.add(faCog);
		library.add(faCogs);
		library.add(faCouch);
		library.add(faCube);
		library.add(faCubes);
		library.add(faDesktop);
		library.add(faEllipsisV);
		library.add(faEllipsisH);
		library.add(faEnvelope);
		library.add(faEthernet);
		library.add(faExclamation);
		library.add(faExclamationCircle);
		library.add(faExclamationTriangle);
		library.add(faFan);
		library.add(faFile);
		library.add(faFolder);
		library.add(faFolderPlus);
		library.add(faGamepad);
		library.add(faGlobe);
		library.add(faHome);
		library.add(faHotTub);
		library.add(faInfo);
		library.add(faInfoCircle);
		library.add(faKey);
		library.add(faLightbulb);
		library.add(faLock);
		library.add(faMagic);
		library.add(faMapMarkerAlt);
		library.add(faMicrochip);
		library.add(faMicrophoneAlt);
		library.add(faMinus);
		library.add(faMinusCircle);
		library.add(faMobile);
		library.add(faPauseCircle);
		library.add(faPencilAlt);
		library.add(faPlayCircle);
		library.add(faPlug);
		library.add(faPlus);
		library.add(faPlusCircle);
		library.add(faPowerOff);
		library.add(faProjectDiagram);
		library.add(faQuestionCircle);
		library.add(faRobot);
		library.add(faSatelliteDish);
		library.add(faSearch);
		library.add(faShower);
		library.add(faSignOutAlt);
		library.add(faSlidersH);
		library.add(faStar);
		library.add(faStopCircle);
		library.add(faStore);
		library.add(faSun);
		library.add(faSyncAlt);
		library.add(faSwimmingPool);
		library.add(faTableTennis);
		library.add(faTachometerAlt);
		library.add(faThermometerHalf);
		library.add(faTrashAlt);
		library.add(faTimes);
		library.add(faTint);
		library.add(faToggleOn);
		library.add(faToilet);
		library.add(faTv);
		library.add(faTrash);
		library.add(faUnlock);
		library.add(faUser);
		library.add(faUserCircle);
		library.add(faUsers);
		library.add(faUserShield);
		library.add(faWifi);
		library.add(faWindowClose);

		library.add(faFacebook);
		library.add(faGithub);
		library.add(faTwitter);
	},
};
