#!/usr/bin/env node
/**
 * Generates a trimmed Iconify icon collection containing only the icon ids
 * that the application actually references via `<Icon icon="prefix:name" />`
 * call sites, and writes it as a committed TypeScript module.
 *
 * Why: `@iconify/vue`'s <Icon> component falls back to the Iconify network API
 * (https://api.iconify.design) for any icon id it does not already have data
 * for. MiniServer is a self-hosted LAN appliance and must render icons with
 * no internet egress, so the icons this app uses have to be registered ahead
 * of time via `addCollection()` (see main.ts). Bundling the full fa6-solid /
 * fa6-regular / fa6-brands collections to cover a few dozen call sites would
 * needlessly bloat the build (~1400 icons in fa6-solid alone), so this script
 * subsets each collection down to only the ids that are actually used.
 *
 * Usage:
 *   node scripts/generate-icons.mjs
 *   node_modules/.bin/prettier --write src/FastyBird/Core/Application/assets/icons.generated.ts
 *
 * Regenerate this file whenever icon usage changes -- a new, removed, or
 * renamed `<Icon icon="fa6-...:...">` call site -- and commit the result. The
 * output is consumed by src/FastyBird/Core/Application/assets/main.ts before
 * the app mounts.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getIcons } from '@iconify/utils';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = join(SCRIPT_DIR, '..');
const SRC_DIR = join(ROOT, 'src', 'FastyBird');
const OUTPUT_FILE = join(ROOT, 'src', 'FastyBird', 'Core', 'Application', 'assets', 'icons.generated.ts');

// Kept in sync with the audit command from the design spec / final review:
//   grep -rhoE "fa6-(solid|regular|brands):[a-z0-9-]+" --include='*.ts' --include='*.vue' src/FastyBird | sort -u
const ICON_PATTERN = /fa6-(solid|regular|brands):[a-z0-9-]+/g;
const SCAN_EXTENSIONS = new Set(['.ts', '.vue']);

/**
 * @param {string} dir
 * @param {string[]} files
 * @returns {string[]}
 */
function collectFiles(dir, files = []) {
	for (const entry of readdirSync(dir)) {
		const fullPath = join(dir, entry);
		const stats = statSync(fullPath);

		if (stats.isDirectory()) {
			collectFiles(fullPath, files);
		} else if (SCAN_EXTENSIONS.has(extname(fullPath))) {
			files.push(fullPath);
		}
	}

	return files;
}

/**
 * @returns {string[]} sorted, de-duplicated `prefix:name` icon ids
 */
function collectIconIds() {
	const ids = new Set();

	for (const file of collectFiles(SRC_DIR)) {
		const contents = readFileSync(file, 'utf8');
		const matches = contents.match(ICON_PATTERN);

		if (matches) {
			for (const match of matches) {
				ids.add(match);
			}
		}
	}

	return [...ids].sort();
}

/**
 * @param {string[]} ids
 * @returns {Map<string, string[]>} prefix -> sorted icon names
 */
function groupByPrefix(ids) {
	const grouped = new Map();

	for (const id of ids) {
		const [prefix, name] = id.split(':');

		if (!grouped.has(prefix)) {
			grouped.set(prefix, []);
		}

		grouped.get(prefix).push(name);
	}

	return grouped;
}

const ids = collectIconIds();
const grouped = groupByPrefix(ids);
const prefixes = [...grouped.keys()].sort();
const collections = [];

for (const prefix of prefixes) {
	const names = grouped.get(prefix);
	const collectionPath = join(ROOT, 'node_modules', '@iconify', 'json', 'json', `${prefix}.json`);
	const collectionData = JSON.parse(readFileSync(collectionPath, 'utf8'));

	const subset = getIcons(collectionData, names, true);

	if (!subset) {
		throw new Error(`generate-icons: collection "${prefix}" resolved no icons at all`);
	}

	if (subset.not_found && subset.not_found.length > 0) {
		throw new Error(`generate-icons: icon ids not found in "${prefix}": ${subset.not_found.join(', ')}`);
	}

	delete subset.not_found;

	collections.push(subset);
}

const iconifyJsonVersion = JSON.parse(readFileSync(join(ROOT, 'node_modules', '@iconify', 'json', 'package.json'), 'utf8')).version;

const summary = collections.map((collection) => `${Object.keys(collection.icons).length} ${collection.prefix}`).join(', ');

const headerLines = [
	'// GENERATED FILE -- do not edit by hand.',
	'//',
	'// Generated by `node scripts/generate-icons.mjs` from `@iconify/json`' + `@${iconifyJsonVersion}.`,
	'// Contains only the Iconify icon ids referenced by `<Icon icon="..." />` call',
	'// sites under src/FastyBird (see scripts/generate-icons.mjs for the exact scan',
	'// and rationale), registered offline via addCollection() in main.ts so the app',
	'// never falls back to the https://api.iconify.design runtime loader.',
	'//',
	'// Regenerate whenever icon usage changes, and commit the result:',
	'//   node scripts/generate-icons.mjs',
	'//   node_modules/.bin/prettier --write src/FastyBird/Core/Application/assets/icons.generated.ts',
	'//',
	`// Icon ids: ${ids.length} (${summary}).`,
	'',
	"import type { IconifyJSON } from '@iconify/types';",
	'',
	`export const iconCollections: IconifyJSON[] = ${JSON.stringify(collections, null, 2)};`,
	'',
];

writeFileSync(OUTPUT_FILE, headerLines.join('\n'));

console.log(`generate-icons: wrote ${ids.length} icon ids across ${collections.length} collections to ${relative(ROOT, OUTPUT_FILE)}`);
