<?php declare(strict_types = 1);

/**
 * E5.8 (#640): split Configuration and type each capability's configuration (#460 §3.9, census
 * T10). The change list format is documented in tools/api-surface.php.
 *
 * T10.1: FastyBird\Core\Configuration mixed the Security settings with the timestampable ones.
 * The type moves to FastyBird\Core\Security\Configuration, which keeps the token and
 * application half (every mention -- HasAuthorization and BasePresenter's injected property and
 * inject method -- follows the move), and the timestampable half becomes
 * FastyBird\Core\Persistence\TimestampableConfiguration, which the timestampable driver takes.
 *
 * T10.2: each configurable capability's schema is cast to a typed class instead of a stdClass:
 * FastyBird\Core\<Capability>\DI\Config for the section and
 * FastyBird\Core\<Capability>\DI\Config\<Path> for each nested structure, 8 + 24 = 32 new
 * types, all final readonly with public promoted properties. The services they are read into
 * are DI, not API: they are in the DI snapshot, not here.
 */

return [
	'renamed' => [
		// census T10.1: the root type is the Security half; every mention follows it
		'FastyBird\\Core\\Configuration' => 'FastyBird\\Core\\Security\\Configuration',
	],
	'removed' => [
		// the timestampable half, now FastyBird\Core\Persistence\TimestampableConfiguration
		'FastyBird\\Core\\Security\\Configuration::$autoMapField',
		'FastyBird\\Core\\Security\\Configuration::$dbFieldType',
		'FastyBird\\Core\\Security\\Configuration::$lazyAssociation',
		'FastyBird\\Core\\Security\\Configuration::autoMapField()',
		'FastyBird\\Core\\Security\\Configuration::useLazyAssociation()',
	],
	'added' => [
		'FastyBird\\Core\\Api\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'meta' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Api\\DI\\Config\\Meta',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$meta' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\Api\\DI\\Config\\Meta',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Api\\DI\\Config\\Meta' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'author' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array|string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'copyright' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$author' => [
							'position' => 0,
							'type' => 'array|string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$copyright' => [
							'position' => 1,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Clock\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'frozen' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'mixed',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'system' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'timeZone' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$timeZone' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$system' => [
							'position' => 1,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$frozen' => [
							'position' => 2,
							'type' => 'mixed',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Documents\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'excludePaths' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'mapping' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$mapping' => [
							'position' => 0,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$excludePaths' => [
							'position' => 1,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Http\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'cors' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Http\\DI\\Config\\Cors',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'server' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Http\\DI\\Config\\Server',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'static' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Http\\DI\\Config\\StaticFiles',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$static' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\Http\\DI\\Config\\StaticFiles',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$server' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\Http\\DI\\Config\\Server',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$cors' => [
							'position' => 2,
							'type' => 'FastyBird\\Core\\Http\\DI\\Config\\Cors',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Http\\DI\\Config\\Cors' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'allow' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Http\\DI\\Config\\CorsAllow',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'enabled' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$enabled' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$allow' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\Http\\DI\\Config\\CorsAllow',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Http\\DI\\Config\\CorsAllow' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'credentials' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'headers' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'methods' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'origin' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$origin' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$methods' => [
							'position' => 1,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$credentials' => [
							'position' => 2,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$headers' => [
							'position' => 3,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Http\\DI\\Config\\Server' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'address' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'certificate' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'port' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$address' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$port' => [
							'position' => 1,
							'type' => 'int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$certificate' => [
							'position' => 2,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Http\\DI\\Config\\StaticFiles' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'enabled' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'publicRoot' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$publicRoot' => [
							'position' => 0,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$enabled' => [
							'position' => 1,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Logging\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'console' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\Console',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'rotatingFile' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\RotatingFile',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'sentry' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\Sentry',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'stdOut' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\StdOut',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$rotatingFile' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\RotatingFile',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$stdOut' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\StdOut',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$console' => [
							'position' => 2,
							'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\Console',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$sentry' => [
							'position' => 3,
							'type' => 'FastyBird\\Core\\Logging\\DI\\Config\\Sentry',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Logging\\DI\\Config\\Console' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'enabled' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'level' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'Monolog\\Level|int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$enabled' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$level' => [
							'position' => 1,
							'type' => 'Monolog\\Level|int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Logging\\DI\\Config\\RotatingFile' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'enabled' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'filename' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'level' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'Monolog\\Level|int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$enabled' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$level' => [
							'position' => 1,
							'type' => 'Monolog\\Level|int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$filename' => [
							'position' => 2,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Logging\\DI\\Config\\Sentry' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'dsn' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'level' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'Monolog\\Level|int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$dsn' => [
							'position' => 0,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$level' => [
							'position' => 1,
							'type' => 'Monolog\\Level|int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Logging\\DI\\Config\\StdOut' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'enabled' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'level' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'Monolog\\Level|int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$enabled' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$level' => [
							'position' => 1,
							'type' => 'Monolog\\Level|int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Persistence\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'timestampable' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Persistence\\DI\\Config\\Timestampable',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$timestampable' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\Persistence\\DI\\Config\\Timestampable',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Persistence\\DI\\Config\\Timestampable' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'autoMapField' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'dbFieldType' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'lazyAssociation' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$lazyAssociation' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$autoMapField' => [
							'position' => 1,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$dbFieldType' => [
							'position' => 2,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Persistence\\TimestampableConfiguration' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'autoMapField' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'dbFieldType' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'lazyAssociation' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$lazyAssociation' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => true,
							'default' => 'false',
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$autoMapField' => [
							'position' => 1,
							'type' => 'bool',
							'optional' => true,
							'default' => 'false',
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$dbFieldType' => [
							'position' => 2,
							'type' => 'string',
							'optional' => true,
							'default' => '\'datetime_immutable\'',
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
				'autoMapField' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => 'bool',
					'parameters' => [],
					'attributes' => [],
					'throws' => [],
				],
				'useLazyAssociation' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => 'bool',
					'parameters' => [],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'application' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Application',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'casbin' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Casbin',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'enable' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Enable',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'services' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Services',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'token' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Token',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$token' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Token',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$enable' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Enable',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$application' => [
							'position' => 2,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Application',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$services' => [
							'position' => 3,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Services',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$casbin' => [
							'position' => 4,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\Casbin',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\Application' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'homeUrl' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'signInUrl' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$signInUrl' => [
							'position' => 0,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$homeUrl' => [
							'position' => 1,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\Casbin' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'model' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'policy' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$model' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$policy' => [
							'position' => 1,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\Enable' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'casbin' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\EnableCasbin',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'doctrine' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\EnableDoctrine',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'middleware' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'nette' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\Security\\DI\\Config\\EnableNette',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$middleware' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$doctrine' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\EnableDoctrine',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$casbin' => [
							'position' => 2,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\EnableCasbin',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$nette' => [
							'position' => 3,
							'type' => 'FastyBird\\Core\\Security\\DI\\Config\\EnableNette',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\EnableCasbin' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'database' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$database' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\EnableDoctrine' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'mapping' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'models' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$mapping' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$models' => [
							'position' => 1,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\EnableNette' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'application' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$application' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\Services' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'identity' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$identity' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\Security\\DI\\Config\\Token' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'issuer' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'signature' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$issuer' => [
							'position' => 0,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$signature' => [
							'position' => 1,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'access' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\Access',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'loop' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'Nette\\DI\\Definitions\\Statement|string|null',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'mapping' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'routes' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'server' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\Server',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'storage' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\Storage',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$storage' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\Storage',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$server' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\Server',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$routes' => [
							'position' => 2,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$mapping' => [
							'position' => 3,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$loop' => [
							'position' => 4,
							'type' => 'Nette\\DI\\Definitions\\Statement|string|null',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$access' => [
							'position' => 5,
							'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\Access',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config\\Access' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'keys' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'origins' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => '?string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$keys' => [
							'position' => 0,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$origins' => [
							'position' => 1,
							'type' => '?string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config\\Server' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'address' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'httpHost' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'port' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'secured' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\ServerSecured',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$httpHost' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$port' => [
							'position' => 1,
							'type' => 'int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$address' => [
							'position' => 2,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$secured' => [
							'position' => 3,
							'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\ServerSecured',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config\\ServerSecured' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'enable' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'bool',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'sslSettings' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'array',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$enable' => [
							'position' => 0,
							'type' => 'bool',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$sslSettings' => [
							'position' => 1,
							'type' => 'array',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config\\Storage' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'clients' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\StorageClients',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'topics' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\StorageTopics',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$clients' => [
							'position' => 0,
							'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\StorageClients',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$topics' => [
							'position' => 1,
							'type' => 'FastyBird\\Core\\WebSockets\\DI\\Config\\StorageTopics',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config\\StorageClients' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'driver' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'ttl' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$driver' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$ttl' => [
							'position' => 1,
							'type' => 'int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
		'FastyBird\\Core\\WebSockets\\DI\\Config\\StorageTopics' => [
			'kind' => 'class',
			'final' => true,
			'abstract' => false,
			'readonly' => true,
			'parent' => null,
			'interfaces' => [],
			'traits' => [],
			'attributes' => [],
			'backing' => null,
			'cases' => [],
			'constants' => [],
			'properties' => [
				'driver' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'string',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
				'ttl' => [
					'visibility' => 'public',
					'set' => 'protected',
					'static' => false,
					'readonly' => true,
					'type' => 'int',
					'hasDefault' => false,
					'default' => null,
					'promoted' => true,
					'virtual' => false,
					'final' => false,
					'abstract' => false,
					'hooks' => [],
					'attributes' => [],
				],
			],
			'methods' => [
				'__construct' => [
					'visibility' => 'public',
					'static' => false,
					'abstract' => false,
					'final' => false,
					'byRef' => false,
					'return' => null,
					'parameters' => [
						'$driver' => [
							'position' => 0,
							'type' => 'string',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
						'$ttl' => [
							'position' => 1,
							'type' => 'int',
							'optional' => false,
							'default' => null,
							'defaultConstant' => null,
							'variadic' => false,
							'byRef' => false,
							'promoted' => true,
							'attributes' => [],
						],
					],
					'attributes' => [],
					'throws' => [],
				],
			],
		],
	],
	'changed' => [
		'FastyBird\\Core\\Persistence\\Mapping\\Driver\\Timestampable::__construct()' => [
			// the timestampable driver takes the Persistence half
			'parameters.$configuration.type' => 'FastyBird\\Core\\Persistence\\TimestampableConfiguration',
		],
		'FastyBird\\Core\\Security\\Configuration::__construct()' => [
			// the timestampable parameters leave with the Persistence half; the two application URLs
			// move up behind the four enable flags, in the order they had
			'-parameters.$lazyAssociation' => null,
			'-parameters.$autoMapField' => null,
			'-parameters.$dbFieldType' => null,
			'parameters.$applicationSignInUrl.position' => 7,
			'parameters.$applicationHomeUrl.position' => 8,
		],
	],
];
