<?php declare(strict_types = 1);

/**
 * E5.12 (#644): Core's accessor pairs become properties (#460 §3.10, census T6, as amended by
 * #671, #672 and #673). The change list format is documented in tools/api-surface.php.
 *
 * Every getter and setter of the 26 in-scope T6 rows is removed, and the property it wrapped is
 * added (it was private, so the base did not record it) or changed (it was protected, so the base
 * recorded it). The `set` visibility each row ends with:
 *
 *   A, a typed public property (`set` public):
 *     1  Documents\Events\PreLoad::$data                       promoted
 *     2  Documents\Mapping\ClassMetadata::$owningEntity
 *     3  Documents\Mapping\ClassMetadata::$isMappedSuperclass
 *     4  Documents\Mapping\ClassMetadata::$inheritanceType
 *     7  EventLoop\Status::$running                            renamed from the private $status
 *    12  Http\Routing\Router::$basePath
 *    29  Security\Identity\UserStorage::$identity
 *    36  WebSockets\Entities\WebSocket::$established          promoted
 *    37  WebSockets\Entities\WebSocket::$closing              promoted
 *    38  WebSockets\Handshake\Request::$protocolVersion       `float`, as stored; the getter said float|null
 *
 *   B, asymmetric visibility:
 *     5  Documents\Mapping\Driver\AttributeDriver::$fileExtension      public private(set)
 *     6  Documents\Mapping\Driver\MappingDriverChain::$defaultDriver   public private(set)
 *     8  Http\Entity::$data                                             public protected(set), promoted; `set` stays protected
 *     9  Http\Exceptions\Http::$title                                   public protected(set); `set` stays protected (#673)
 *    10  Http\Exceptions\Http::$description                             public protected(set); `set` stays protected (#673)
 *    13  Persistence\Crud\CrudManager::$flush                           public protected(set)
 *    17  Phone\Entities\Phone::$extension                               public private(set)
 *    18  Phone\Entities\Phone::$italianLeadingZero                      public private(set)
 *    19  Phone\Entities\Phone::$numberOfLeadingZeros                    public private(set), still
 *        hasDefault false, as in base.json (#672): only visibility, set and final change
 *    20  Phone\Entities\Phone::$timeZones                               public private(set)
 *    40  WebSockets\Server\Configuration::$port                         public private(set), promoted (not readonly)
 *    41  WebSockets\Server\Configuration::$address                      public private(set), promoted (not readonly)
 *    PHP reports a private(set) property as final, hence `final` on the private(set) rows.
 *
 *   #673, a consequence of rows 9 and 10, not new rows: Http\Exceptions\HttpNotFound and
 *   HttpMethodNotAllowed redeclare $title and $description as public protected(set) with their
 *   default values unchanged (a private(set) parent property is implicitly final and could not
 *   be redeclared). 4 visibility changes, protected -> public.
 *
 *   H, an interface property `{ get; set; }` that the implementing class satisfies with a plain
 *   public property:
 *    31  WebSockets\Controllers\DispatchRequest::$controllerName   (Request::$controllerName)
 *    32  WebSockets\Controllers\DispatchRequest::$parameters       (Request::$parameters)
 *    33  WebSockets\Entities\ConnectedClient::$httpHeadersReceived (Client::$httpHeadersReceived)
 *    34  WebSockets\Entities\ConnectedClient::$httpBuffer          (Client::$httpBuffer)
 *    Request's constructor keeps its $name and $params parameters; they are no longer promoted.
 */

return [
	'removed' => [
		'FastyBird\\Core\\Documents\\Events\\PreLoad::getData()',
		'FastyBird\\Core\\Documents\\Events\\PreLoad::setData()',
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::getInheritanceType()',
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::getOwningEntity()',
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::isMappedSuperclass()',
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::setInheritanceType()',
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::setIsMappedSuperclass()',
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::setOwningEntity()',
		'FastyBird\\Core\\Documents\\Mapping\\Driver\\AttributeDriver::getFileExtension()',
		'FastyBird\\Core\\Documents\\Mapping\\Driver\\AttributeDriver::setFileExtension()',
		'FastyBird\\Core\\Documents\\Mapping\\Driver\\MappingDriverChain::getDefaultDriver()',
		'FastyBird\\Core\\Documents\\Mapping\\Driver\\MappingDriverChain::setDefaultDriver()',
		'FastyBird\\Core\\EventLoop\\Status::isRunning()',
		'FastyBird\\Core\\EventLoop\\Status::setStatus()',
		'FastyBird\\Core\\Http\\Entity::getData()',
		'FastyBird\\Core\\Http\\Entity::setData()',
		'FastyBird\\Core\\Http\\Exceptions\\Http::getDescription()',
		'FastyBird\\Core\\Http\\Exceptions\\Http::getTitle()',
		'FastyBird\\Core\\Http\\Exceptions\\Http::setDescription()',
		'FastyBird\\Core\\Http\\Exceptions\\Http::setTitle()',
		'FastyBird\\Core\\Http\\Routing\\Router::getBasePath()',
		'FastyBird\\Core\\Http\\Routing\\Router::setBasePath()',
		'FastyBird\\Core\\Persistence\\Crud\\CrudManager::getFlush()',
		'FastyBird\\Core\\Persistence\\Crud\\CrudManager::setFlush()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::getExtension()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::getItalianLeadingZero()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::getNumberOfLeadingZeros()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::getTimeZones()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::setExtension()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::setItalianLeadingZero()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::setNumberOfLeadingZeros()',
		'FastyBird\\Core\\Phone\\Entities\\Phone::setTimeZones()',
		'FastyBird\\Core\\Security\\Identity\\UserStorage::getIdentity()',
		'FastyBird\\Core\\Security\\Identity\\UserStorage::setIdentity()',
		'FastyBird\\Core\\WebSockets\\Controllers\\DispatchRequest::getControllerName()',
		'FastyBird\\Core\\WebSockets\\Controllers\\DispatchRequest::getParameters()',
		'FastyBird\\Core\\WebSockets\\Controllers\\DispatchRequest::setControllerName()',
		'FastyBird\\Core\\WebSockets\\Controllers\\DispatchRequest::setParameters()',
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::getControllerName()',
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::getParameters()',
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::setControllerName()',
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::setParameters()',
		'FastyBird\\Core\\WebSockets\\Entities\\Client::getHttpBuffer()',
		'FastyBird\\Core\\WebSockets\\Entities\\Client::isHttpHeadersReceived()',
		'FastyBird\\Core\\WebSockets\\Entities\\Client::setHttpBuffer()',
		'FastyBird\\Core\\WebSockets\\Entities\\Client::setHttpHeadersReceived()',
		'FastyBird\\Core\\WebSockets\\Entities\\ConnectedClient::getHttpBuffer()',
		'FastyBird\\Core\\WebSockets\\Entities\\ConnectedClient::isHttpHeadersReceived()',
		'FastyBird\\Core\\WebSockets\\Entities\\ConnectedClient::setHttpBuffer()',
		'FastyBird\\Core\\WebSockets\\Entities\\ConnectedClient::setHttpHeadersReceived()',
		'FastyBird\\Core\\WebSockets\\Entities\\WebSocket::isClosing()',
		'FastyBird\\Core\\WebSockets\\Entities\\WebSocket::isEstablished()',
		'FastyBird\\Core\\WebSockets\\Entities\\WebSocket::setClosing()',
		'FastyBird\\Core\\WebSockets\\Entities\\WebSocket::setEstablished()',
		'FastyBird\\Core\\WebSockets\\Handshake\\Request::getProtocolVersion()',
		'FastyBird\\Core\\WebSockets\\Handshake\\Request::setProtocolVersion()',
		'FastyBird\\Core\\WebSockets\\Server\\Configuration::getAddress()',
		'FastyBird\\Core\\WebSockets\\Server\\Configuration::getPort()',
		'FastyBird\\Core\\WebSockets\\Server\\Configuration::setAddress()',
		'FastyBird\\Core\\WebSockets\\Server\\Configuration::setPort()',
	],
	'added' => [
		'FastyBird\\Core\\Documents\\Events\\PreLoad::$data' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'array',
			'hasDefault' => false,
			'default' => null,
			'promoted' => true,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::$inheritanceType' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'int',
			'hasDefault' => true,
			'default' => '0',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::$isMappedSuperclass' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => true,
			'default' => 'false',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Documents\\Mapping\\ClassMetadata::$owningEntity' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => '?string',
			'hasDefault' => true,
			'default' => 'null',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Documents\\Mapping\\Driver\\AttributeDriver::$fileExtension' => [
			'visibility' => 'public',
			'set' => 'private',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => true,
			'default' => '\'.php\'',
			'promoted' => false,
			'virtual' => false,
			'final' => true,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Documents\\Mapping\\Driver\\MappingDriverChain::$defaultDriver' => [
			'visibility' => 'public',
			'set' => 'private',
			'static' => false,
			'readonly' => false,
			'type' => '?FastyBird\\Core\\Documents\\Mapping\\Driver\\AttributeDriver',
			'hasDefault' => true,
			'default' => 'null',
			'promoted' => false,
			'virtual' => false,
			'final' => true,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\EventLoop\\Status::$running' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => true,
			'default' => 'false',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Http\\Routing\\Router::$basePath' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => true,
			'default' => '\'\'',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Persistence\\Crud\\CrudManager::$flush' => [
			'visibility' => 'public',
			'set' => 'protected',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => true,
			'default' => 'true',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\Security\\Identity\\UserStorage::$identity' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => '?FastyBird\\Core\\Security\\Identity\\UserIdentity',
			'hasDefault' => true,
			'default' => 'null',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Controllers\\DispatchRequest::$controllerName' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => true,
			'final' => false,
			'abstract' => true,
			'hooks' => [
				'get' => [
					'final' => false,
					'abstract' => true,
					'return' => 'string',
				],
				'set' => [
					'final' => false,
					'abstract' => true,
					'parameter' => 'string',
				],
			],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Controllers\\DispatchRequest::$parameters' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'array',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => true,
			'final' => false,
			'abstract' => true,
			'hooks' => [
				'get' => [
					'final' => false,
					'abstract' => true,
					'return' => 'array',
				],
				'set' => [
					'final' => false,
					'abstract' => true,
					'parameter' => 'array',
				],
			],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::$controllerName' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::$parameters' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'array',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Entities\\Client::$httpBuffer' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => true,
			'default' => '\'\'',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Entities\\Client::$httpHeadersReceived' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => true,
			'default' => 'false',
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Entities\\ConnectedClient::$httpBuffer' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => true,
			'final' => false,
			'abstract' => true,
			'hooks' => [
				'get' => [
					'final' => false,
					'abstract' => true,
					'return' => 'string',
				],
				'set' => [
					'final' => false,
					'abstract' => true,
					'parameter' => 'string',
				],
			],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Entities\\ConnectedClient::$httpHeadersReceived' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => true,
			'final' => false,
			'abstract' => true,
			'hooks' => [
				'get' => [
					'final' => false,
					'abstract' => true,
					'return' => 'bool',
				],
				'set' => [
					'final' => false,
					'abstract' => true,
					'parameter' => 'bool',
				],
			],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Entities\\WebSocket::$closing' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => false,
			'default' => null,
			'promoted' => true,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Entities\\WebSocket::$established' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'bool',
			'hasDefault' => false,
			'default' => null,
			'promoted' => true,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Handshake\\Request::$protocolVersion' => [
			'visibility' => 'public',
			'set' => 'public',
			'static' => false,
			'readonly' => false,
			'type' => 'float',
			'hasDefault' => false,
			'default' => null,
			'promoted' => false,
			'virtual' => false,
			'final' => false,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Server\\Configuration::$address' => [
			'visibility' => 'public',
			'set' => 'private',
			'static' => false,
			'readonly' => false,
			'type' => 'string',
			'hasDefault' => false,
			'default' => null,
			'promoted' => true,
			'virtual' => false,
			'final' => true,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
		'FastyBird\\Core\\WebSockets\\Server\\Configuration::$port' => [
			'visibility' => 'public',
			'set' => 'private',
			'static' => false,
			'readonly' => false,
			'type' => 'int',
			'hasDefault' => false,
			'default' => null,
			'promoted' => true,
			'virtual' => false,
			'final' => true,
			'abstract' => false,
			'hooks' => [],
			'attributes' => [],
		],
	],
	'changed' => [
		'FastyBird\\Core\\Http\\Entity::$data' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Http\\Exceptions\\Http::$description' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Http\\Exceptions\\Http::$title' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Http\\Exceptions\\HttpMethodNotAllowed::$description' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Http\\Exceptions\\HttpMethodNotAllowed::$title' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Http\\Exceptions\\HttpNotFound::$description' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Http\\Exceptions\\HttpNotFound::$title' => [
			'visibility' => 'public',
		],
		'FastyBird\\Core\\Phone\\Entities\\Phone::$extension' => [
			'visibility' => 'public',
			'set' => 'private',
			'final' => true,
		],
		'FastyBird\\Core\\Phone\\Entities\\Phone::$italianLeadingZero' => [
			'visibility' => 'public',
			'set' => 'private',
			'final' => true,
		],
		'FastyBird\\Core\\Phone\\Entities\\Phone::$numberOfLeadingZeros' => [
			'visibility' => 'public',
			'set' => 'private',
			'final' => true,
		],
		'FastyBird\\Core\\Phone\\Entities\\Phone::$timeZones' => [
			'visibility' => 'public',
			'set' => 'private',
			'final' => true,
		],
		'FastyBird\\Core\\WebSockets\\Controllers\\Request::__construct()' => [
			'parameters.$name.promoted' => false,
			'parameters.$params.promoted' => false,
		],
	],
];
