; SUPERVISORD CONFIG

[unix_http_server]
file = /var/run/supervisor.sock
chmod = 0700

[supervisord]
logfile = /dev/stdout
logfile_maxbytes = 0
pidfile = /var/run/supervisord.pid
childlogdir = /var/log/supervisor
nodaemon = true
user = root

[supervisorctl]
serverurl = unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[inet_http_server]
port = 0.0.0.0:9001

[include]
files = /app/var/config/supervisor/*.conf

; APPLICATION PROGRAMS

[program:php-fpm]
command = php-fpm -F
user = root
autostart = true
autorestart = true

[program:nginx]
command = nginx -g "daemon off;"
user = root
autostart = true
autorestart = true

[program:ws-server]
command = php /app/bin/fb-console.php fb:ws-server:start
user = www-data
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = /app/var/logs/ws-server.log

[program:exchange]
command = php /app/bin/fb-console.php fb:devices-module:exchange -n
user = www-data
autostart = true
autorestart = true
redirect_stderr = true
stdout_logfile = /app/var/logs/exchange.log

[eventlistener:subprocess-watcher]
command = php /app/bin/fb-supervisor.php
numprocs = 1
events = PROCESS_STATE_EXITED,PROCESS_STATE_STOPPED,PROCESS_STATE_FATAL
autostart = true
autorestart = unexpected
